name: mileage_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.4+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  get: ^4.7.2
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  # image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/